- name: Verificar atualizacoes
  hosts: 10.50.10.10
  become: yes
  tasks:
    - name: Atualizar cache de pacotes
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Verificar atualizacoes disponiveis
      apt:
        upgrade: safe
        update_cache: yes
        cache_valid_time: 3600
      register: upgrade_result
      when: ansible_distribution == 'Ubuntu'

    - name: Mostrar pacotes disponiveis para atualizacao
      debug:
        var: upgrade_result
      when: upgrade_result | changed
